### ISSUE TITLE
Unable to open in 4.27

### ISSUE THREAD

**Issue by QuantifiableGaming** [MarkusTheOrt/Spotify-Unreal-Controls#1]
Downloaded and attempting to open Spotify.uproject when it states that it requires the Bridge Plug in 

I cant seem to find it in UE or on the market place - can you let us know where it is located or include in the files? 

Thanks
![Screenshot 2021-11-29 005450](https://user-images.githubusercontent.com/78249810/143777949-b9020580-56b9-4036-a11e-0448eac93ed0.png)

**Comment by MarkusTheOrt** [comment]
Are you sure you downloaded the 4.26 branch? I can open it normally and I have no plugins installed. While it is defaulted in unreal 5 EA. Make sure you download the 4.26 branch (it is compatible with 4.27)
![Branches](https://static.ort.dev/pub/brave_8XGOvdtDnl.png)

**Comment by QuantifiableGaming** [comment]
Thanks sorry - I missed that
